### ISSUE TITLE
Universal ID based on location, altitude and atmospheric exposure

### ISSUE THREAD

**Issue by vgeorge** [openaq/project-universal-stationID#9]
I would like to propose an URL-friendly id based on three properties: location, altitude and atmospheric exposure. The pattern would be:

`<location>-<altitude>-<atm_exposure>`

Where:

- `location`: [Open Location Code (OLC)](https://en.wikipedia.org/wiki/Open_Location_Code) identifier. This is a open source global geocode, platform independent, URL-friendly, with maximum precision of 3 x 3 meters. Please refer to the [website](https://plus.codes) and [FAQ](https://plus.codes/faq) for more details;
- `altitude`: A integer representing sensor's altitude;
- `atm_exposure`: Indicates type or class of sensor's atmospheric exposure. It is necessary to differentiate closeby sensors, for example, one attached outside a building, near a window, to other inside the building, close to that window.  Might be 0 or 1, if representing indoor/outdoor condition is sufficient, or might be class based to represent more specific cases, like under marquises, tunnels, etc.

Here is a example of a locality:

https://plus.codes/588MC8QV+9J3

A sensor inside "9 de Julho" tunnel, the lowest level, would have the following ID:

`588MC8QV+9J3-720-0`

A sensor in the same 3x3m projected square, but inside a museum's room:

`588MC8QV+9J3-760-0`

Another sensor at the top of the museum:

`588MC8QV+9J3-790-1`

This proposal has a limitation when there is more than one sensor with the same atmospheric exposure sharing the same square of 3 x 3 m, which I imagine is difficult to happen in the context of OpenAQ.

**Comment by olafveerman** [comment]
Thanks @vgeorge 

1. what's the advantage over using lat/lon for the ID?
2. for the large majority of stations, altitude and atmospheric exposure will not be known. What's the fallback for these cases?

**Comment by RocketD0g** [comment]
One other thing to keep in mind is that most gov't stations do report more than one type of pollutant, which means, in many cases, a little 3mx3m area will have more than one type of monitor.

**Comment by maschu09** [comment]
For reasons discussed in #7 I sympathize with the idea to use plus codes. @RocketD0g 's argument that there may be more than one monitor in a 3x3 area doesn't count against this as we don't want to identify monitors but "stations" here. Of course it is debatable what exactly constitutes a "station". Some sites may have multiple locations for monitors, and are oceangoing vessels considered a "station"?
One advantage of plus codes could be that they are resolvable.

**Comment by maschu09** [comment]
Upon trying to come up with a summary (#10) here a suggestion for the part after the plus code:

- if sampling altitude (i.e. height of inlet line) is known, provide this as numeric value in m with 3 digits
- if sampling altitude is unknown, use letters; "A", "B", "C", etc. if there is a need to distinguish "stations" 
- as we only care about outdoor air pollution monitors in OpenAQ (or am I missing something here?) there should be no need to encode exposure in the universal stationID. This clearly is relevant information but should go into other metadata.

**Comment by vgeorge** [comment]
Current approach for ids is available here: https://github.com/openaq/project-universal-stationID/issues/12.
